### ISSUE TITLE
Proof of Wedderburn Theorem

### ISSUE THREAD

**Issue by Properzi** [vendramin/representation#3]
I would say (and it's shorter):
[...] $(A/J(A))^m=\{0\}$. Hence $A^m\subseteq J(A)$ and $A^{mn}=(A^m)^n\subseteq (J(A))^n=\{0\}$. Thus $A$ is nilpotent.

**Comment by vendramin** [comment]
I agree yours is better. But I will leave my very elementary and over-detailed proof :)
